
import java.util.Date;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell 7404
 */
public class Barclays extends javax.swing.JFrame {

    /**
     * Creates new form Barclays
     */
    public Barclays() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CustomerNamelbl = new javax.swing.JLabel();
        AccountNoLabel = new javax.swing.JLabel();
        AccountNameLbl = new javax.swing.JLabel();
        MobileNoLbl = new javax.swing.JLabel();
        CurrencyComboBox = new javax.swing.JComboBox<>();
        BranchNameComboBox = new javax.swing.JComboBox<>();
        NarrativeComboBox = new javax.swing.JComboBox<>();
        CustomerNameTxtField = new javax.swing.JTextField();
        AccountNoTxtField = new javax.swing.JTextField();
        AccountNameTxtField = new javax.swing.JTextField();
        MobileNoTxtField = new javax.swing.JTextField();
        PrintReceiptBtn = new javax.swing.JButton();
        GenerateReceiptBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        AdmissionNoLbl = new javax.swing.JLabel();
        AdmissionNoTxtField = new javax.swing.JTextField();
        FeesAmountLbl = new javax.swing.JLabel();
        FeesAmountTxtField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        IdNoLbl = new javax.swing.JLabel();
        IdNoTxtField = new javax.swing.JTextField();
        CurrencyLbl = new javax.swing.JLabel();
        NarrativeLbl = new javax.swing.JLabel();
        BranchNameLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ExitBtn = new javax.swing.JToggleButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barclays.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 3, 62)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("BARCLAYS");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel3.setText("Details");

        CustomerNamelbl.setText("Customer Name");

        AccountNoLabel.setText("Account No");

        AccountNameLbl.setText("Account Name");

        MobileNoLbl.setText("Mobile No");

        CurrencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KES", "USD", "EUR", "BITCOINS" }));
        CurrencyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyComboBoxActionPerformed(evt);
            }
        });

        BranchNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Queensway House", "CBD", "Tom mboya", "Ronald Ngala str", "Moi Avenue" }));

        NarrativeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mpesa", "Visa", "Western Union", "Paypal" }));
        NarrativeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NarrativeComboBoxActionPerformed(evt);
            }
        });

        CustomerNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameTxtFieldActionPerformed(evt);
            }
        });

        AccountNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountNameTxtFieldActionPerformed(evt);
            }
        });

        MobileNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNoTxtFieldActionPerformed(evt);
            }
        });

        PrintReceiptBtn.setText("Print Receipt");
        PrintReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintReceiptBtnActionPerformed(evt);
            }
        });

        GenerateReceiptBtn.setText("Generate Receipt");
        GenerateReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReceiptBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        AdmissionNoLbl.setText("Admission No");

        FeesAmountLbl.setText("Fees Amount");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Parent");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Student");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        IdNoLbl.setText("ID No");

        CurrencyLbl.setText("Currency");

        NarrativeLbl.setText("Narrative");

        BranchNameLbl.setText("Branch Name");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BranchNameLbl)
                                        .addGap(37, 37, 37)
                                        .addComponent(BranchNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(301, 301, 301))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(GenerateReceiptBtn)
                                                .addGap(62, 62, 62)
                                                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(NarrativeLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NarrativeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(CurrencyLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CurrencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(49, 49, 49)
                                        .addComponent(PrintReceiptBtn)
                                        .addGap(97, 97, 97)))
                                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CustomerNamelbl)
                                                    .addComponent(AccountNoLabel)
                                                    .addComponent(AccountNameLbl)
                                                    .addComponent(MobileNoLbl)
                                                    .addComponent(AdmissionNoLbl)
                                                    .addComponent(FeesAmountLbl))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(FeesAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(IdNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(CustomerNameTxtField)
                                                        .addComponent(AccountNoTxtField)
                                                        .addComponent(AccountNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(AdmissionNoTxtField)
                                                        .addComponent(MobileNoTxtField))))
                                            .addComponent(IdNoLbl)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton2)
                                        .addGap(41, 41, 41)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerNamelbl)
                            .addComponent(CustomerNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccountNoLabel)
                            .addComponent(AccountNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccountNameLbl)
                            .addComponent(AccountNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MobileNoLbl)
                            .addComponent(MobileNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdmissionNoLbl)
                            .addComponent(AdmissionNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FeesAmountLbl)
                            .addComponent(FeesAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdNoLbl)
                            .addComponent(IdNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BranchNameLbl)
                            .addComponent(BranchNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NarrativeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrencyLbl)
                            .addComponent(CurrencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NarrativeLbl))
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateReceiptBtn)
                    .addComponent(ResetBtn)
                    .addComponent(PrintReceiptBtn)
                    .addComponent(ExitBtn))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrencyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrencyComboBoxActionPerformed

    private void CustomerNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameTxtFieldActionPerformed

    private void AccountNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountNameTxtFieldActionPerformed

    private void MobileNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNoTxtFieldActionPerformed

    private void NarrativeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NarrativeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NarrativeComboBoxActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
       //calling the reset method
       reset();
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // calling enabled function
        enabled();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // calling the disable method
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

     /* public  void random(){
        String s[]={"rono","rerer","gitu","alex","pitta"};
            Random ran =new Random();
            String d=s[ran.nextInt(s.length)];
            System.out.println(d);
    }*/
    

    
    private void GenerateReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReceiptBtnActionPerformed
        
        jTextArea1.setText("*********************************************\n");
        jTextArea1.setText(jTextArea1.getText() + "*            Transaction Details            *\n");
        jTextArea1.setText(jTextArea1.getText() + "*********************************************\n");
        
        Date obj =new Date();
        String date=obj.toString();
       
        jTextArea1.setText(jTextArea1.getText()+ " Date : " +date );
        jTextArea1.setText(jTextArea1.getText()+ "\n Branch Name : " +BranchNameComboBox.getSelectedItem());
        jTextArea1.setText(jTextArea1.getText()+"\n Teller Name : "  + "KOECHV017");
        jTextArea1.setText(jTextArea1.getText()+"\n Transaction No : " + "178");
        jTextArea1.setText(jTextArea1.getText()+"\n Account Name : " +  AccountNameTxtField.getText());
        jTextArea1.setText(jTextArea1.getText()+"\n Account No : " + AccountNoTxtField.getText());
        jTextArea1.setText(jTextArea1.getText()+"\n Commission : "+ "45.0");
        jTextArea1.setText(jTextArea1.getText()+"\n ID No :"+IdNoTxtField.getText() );
        jTextArea1.setText(jTextArea1.getText()+"\n Narrative : "+ NarrativeComboBox.getSelectedItem());
        jTextArea1.setText(jTextArea1.getText()+"\n Admission No : " + AdmissionNoTxtField.getText());
         jTextArea1.setText(jTextArea1.getText()+"\n Currency : " + CurrencyComboBox.getSelectedItem());
      
         jTextArea1.setText(jTextArea1.getText() +"\n*********************************************\n");
        jTextArea1.setText(jTextArea1.getText() + "*            Deposit Details            *\n");
        jTextArea1.setText(jTextArea1.getText() + "*********************************************\n");
        
         jTextArea1.setText(jTextArea1.getText()+" Amount : " +FeesAmountTxtField.getText());
         jTextArea1.setText(jTextArea1.getText() + "\n\n  #************   Signature   ************#");
         
         jTextArea1.setText(jTextArea1.getText() + "\n\n\n\n\n\n  #***************************************#");
         jTextArea1.setText(jTextArea1.getText() + "\n          ©2020 Barclays Bank  ");
         
         // progress bar
       String  change =CustomerNameTxtField.getText();
       //getting the length of the string
        int   pog=change.length();
       //progress bar should have a value of an integer
         jProgressBar1.setValue(pog);
         
    }//GEN-LAST:event_GenerateReceiptBtnActionPerformed

    private void PrintReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintReceiptBtnActionPerformed
        // TODO add your handling code here:
        try{
            jTextArea1.print();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_PrintReceiptBtnActionPerformed


    
    
//creating a disabled method
    public void disable(){
        // ©2020 Barclays Bank    verified internalionallly 
         NarrativeComboBox.setEnabled(true);
        CurrencyComboBox.setEnabled(true);
        BranchNameComboBox.setEnabled(true);
        CustomerNameTxtField.setEnabled(true);
        AccountNoTxtField.setEnabled(true);
        AccountNameTxtField.setEnabled(true);
        MobileNoTxtField.setEnabled(false);
        AdmissionNoTxtField.setEnabled(true);
        FeesAmountTxtField.setEnabled(true);
        IdNoTxtField.setEnabled(false);
       jRadioButton2.setEnabled(false);
       
        
    }
    
    
    
    
// creating enabled method
    public void enabled(){
        
         NarrativeComboBox.setEnabled(true);
        CurrencyComboBox.setEnabled(true);
        BranchNameComboBox.setEnabled(true);
        CustomerNameTxtField.setEnabled(true);
        AccountNoTxtField.setEnabled(true);
        AccountNameTxtField.setEnabled(true);
        MobileNoTxtField.setEnabled(true);
        AdmissionNoTxtField.setEnabled(false);
        FeesAmountTxtField.setEnabled(true);
        IdNoTxtField.setEnabled(true);
       jRadioButton2.setEnabled(true);
       
        
    }



// creating reset method
    public void reset(){
        NarrativeComboBox.setSelectedIndex(0);
        CurrencyComboBox.setSelectedIndex(0);
        BranchNameComboBox.setSelectedIndex(0);
        CustomerNameTxtField.setText("");
        AccountNoTxtField.setText("");
        AccountNameTxtField.setText("");
        MobileNoTxtField.setText("");
        AdmissionNoTxtField.setText("");
        FeesAmountTxtField.setText("");
        IdNoTxtField.setText("");
        jTextArea1.setText(null);
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barclays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barclays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barclays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barclays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barclays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNameLbl;
    private javax.swing.JTextField AccountNameTxtField;
    private javax.swing.JLabel AccountNoLabel;
    private javax.swing.JTextField AccountNoTxtField;
    private javax.swing.JLabel AdmissionNoLbl;
    private javax.swing.JTextField AdmissionNoTxtField;
    private javax.swing.JComboBox<String> BranchNameComboBox;
    private javax.swing.JLabel BranchNameLbl;
    private javax.swing.JComboBox<String> CurrencyComboBox;
    private javax.swing.JLabel CurrencyLbl;
    private javax.swing.JTextField CustomerNameTxtField;
    private javax.swing.JLabel CustomerNamelbl;
    private javax.swing.JToggleButton ExitBtn;
    private javax.swing.JLabel FeesAmountLbl;
    private javax.swing.JTextField FeesAmountTxtField;
    private javax.swing.JButton GenerateReceiptBtn;
    private javax.swing.JLabel IdNoLbl;
    private javax.swing.JTextField IdNoTxtField;
    private javax.swing.JLabel MobileNoLbl;
    private javax.swing.JTextField MobileNoTxtField;
    private javax.swing.JComboBox<String> NarrativeComboBox;
    private javax.swing.JLabel NarrativeLbl;
    private javax.swing.JButton PrintReceiptBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
